audit_header: false
title: "South Dakota's Best Real Estate Training - Michelle Maloney"
description: Michelle Maloney, a top Real Estate Agent in South Dakota, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
client:
  name: Michelle Maloney
  title:
  license_number:
  about_markdown: |
    I've lived in Vermillion since 1988, and I can tell you Vermillion is a GREAT place to live.  I opened Maloney Real Estate because I want to help develop a community, not just sell houses.  I am committed to making your experience the best it can be and look forward to helping you.
  market: South Dakota
  brand: Maloney Real Estate
  brokerage:
  address: 108 East Main Street Vermillion, SD 57069
  phone: 605-677-9006
  phone_type:
  phone2:
  phone2_type:
  email: michelle@realestatemaloney.com
  url: https://www.realestatemaloney.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Maloney Real Estate can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/RealEstateMaloney
  linkedin_url:
  youtube_url:
  twitter_url: https://twitter.com/RealEstateVerm
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/murloney07/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'South Dakota Real Estate Podcast with Michelle Maloney'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the South Dakota Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Maloney Real Estate - your professional South Dakota Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in South Dakota, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Michelle Maloney'

images:
  client_headshot_path: /img/headshot.jpeg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: South Dakota Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#e94724'
  theme_color: '#626366'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#e94724'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
